### ISSUE TITLE
Creating Pflichtenheft

### ISSUE THREAD

**Issue by yetisports** [oasp-forge/oasp4j-enterprise-security#20]
Creating Pflichtenheft with the following structure:
1. Introduction
2. Technical background
3. Functional requirements
4. Non-functional requirements
5. Userinterface
6. Technical Environment
7. Deliverables
8. Legal process

**Comment by hohwille** [comment]
For the security topic there will be very little to say about user-interface. However the access-manager will typically allow to customize the login screen to your own needs. Maybe the same for screens to change password and reset password, optionally view and edit user profile but that is pretty much about it. So that is quite boring.
If we come to the mobile client topic this will be more interesting. The question is if we have another "Pflichtenheft" for that. For the moment I would only focus on the security issue and make progress there. When things are running or members of the team get out of work we will look at the mobile stuff.
