### ISSUE TITLE
download and install openAM

### ISSUE THREAD

**Issue by hohwille** [oasp-forge/oasp4j-enterprise-security#9]
download and install openAM, alongside document the steps and process to get it up and running (in github wiki).

**Comment by hohwille** [comment]
documentation should go here:
https://github.com/oasp-forge/oasp4j-enterprise-security/wiki/guide-installation

**Comment by hohwille** [comment]
When I install OpenDJ with empty DB (not even root DN) and without starting the server on startup then the installation succeeds.
Now, when I call start-sh script I get this error:

> Exception in thread "main" java.lang.ExceptionInInitializerError: A security cla
> ss cannot be found in this JVM because of the following reason: sun.security.x509.CertAndKeyGen
>         at org.opends.server.util.Platform$PlatformIMPL.<clinit>(Platform.java:127)
>         at org.opends.server.util.Platform.<clinit>(Platform.java:80)
>         at org.opends.server.util.CertificateManager.generateSelfSignedCertificate(CertificateManager.java:283)
>         at org.opends.server.admin.AdministrationConnector.createSelfSignedCertificateIfNeeded(AdministrationConnector.java:698)
>         at org.opends.server.core.DirectoryServer.startServer(DirectoryServer.java:1353)
>         at org.opends.server.core.DirectoryServer.main(DirectoryServer.java:9651)

Seems that the code depends on an internal JDK class that is no more available. I tried both with JDK 1.7 and with JDK 1.8 with the same error.

**Comment by nastia2325** [comment]
Hello Jörg, 

because its not possible to use agents on mac I had to install windows over bootcamp. So I also had to install OpenAM, OpenDJ, etc. again and I had the same issue like you (the same error). The problem is that the version of OpenDJ 2.6.0 is not compatible with jdk 1.8. I guess by Julian it runs, because he has a subscription version. Now I installed JDK 1.7 additionaly and set an extra variable OPENDJ_JAVA_HOME = path to jdk 1.7, so OpenDJ uses this Variable at first if it is set. So now everything is working. 

I hope it helps you as well. 

Best Regards
